### ISSUE TITLE
qtconsole does not connect to existing kernel

### ISSUE THREAD

**Issue by huyiqun** [jupyter/qtconsole#115]
It worked just fine and I updated to version 4.2.0 through Anaconda launcher, then I typed `jupyter qtconsole --existing fullpath/to/kernel.json`, it just gave me a blank window:
<img width="680" alt="screen shot 2016-03-27 at 5 22 08 pm" src="https://cloud.githubusercontent.com/assets/10877536/14067926/82d3f704-f440-11e5-8b22-271fa85216b1.png">

`jupyter qtconsole` itself still works as usual.

Using Mac OSX.

**Comment by minrk** [comment]
Should be fixed by #118

**Comment by huyiqun** [comment]
Still seeing a blank window, though. Any additional steps needed to be taken?

**Comment by minrk** [comment]
@huyiqun you are running from master?
