### ISSUE TITLE
Qtconsole not working on Windows and Python 3.8

### ISSUE THREAD

**Issue by ericpre** [jupyter/qtconsole#405]
Similar to #400.

Step to reproduce:
```
conda create -n py38 python
conda activate py38
conda install qtconsole
jupyter qtconsole
```
Gives the following error:
```
ERROR:tornado.application:Exception in callback functools.partial(<function ThreadedZMQSocketChannel.__init__.<locals>.setup_stream at 0x000002079F95B4C0>)
Traceback (most recent call last):
  File "C:\Users\Eric\Miniconda3\envs\py38qt\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\Users\Eric\Miniconda3\envs\py38qt\lib\site-packages\jupyter_client\threaded.py", line 48, in setup_stream
    self.stream = zmqstream.ZMQStream(self.socket, self.ioloop)
  File "C:\Users\Eric\Miniconda3\envs\py38qt\lib\site-packages\zmq\eventloop\zmqstream.py", line 127, in __init__
    self._init_io_state()
  File "C:\Users\Eric\Miniconda3\envs\py38qt\lib\site-packages\zmq\eventloop\zmqstream.py", line 546, in _init_io_state
    self.io_loop.add_handler(self.socket, self._handle_events, self.io_loop.READ)
  File "C:\Users\Eric\Miniconda3\envs\py38qt\lib\site-packages\tornado\platform\asyncio.py", line 99, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Users\Eric\Miniconda3\envs\py38qt\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
```

I don't know where it needs to be fixed and if qtconsole needs a similar fix to the PRs below:
https://github.com/tornadoweb/tornado/issues/2608
https://github.com/jupyter/notebook/pull/5047
https://github.com/ipython/ipykernel/pull/456

conda info:
```

     active environment : py38
    active env location : C:\Users\Eric\Miniconda3\envs\py38
            shell level : 2
       user config file : C:\Users\Eric\.condarc
 populated config files : C:\Users\Eric\.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.4.final.0
       virtual packages : __cuda=10.1
       base environment : C:\Users\Eric\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Eric\Miniconda3\pkgs
                          C:\Users\Eric\.conda\pkgs
                          C:\Users\Eric\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Eric\Miniconda3\envs
                          C:\Users\Eric\.conda\envs
                          C:\Users\Eric\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

```
conda list
```
# packages in environment at C:\Users\Eric\Miniconda3\envs\py38:
#
# Name                    Version                   Build  Channel
backcall                  0.1.0                      py_0    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py38_0    conda-forge
colorama                  0.4.3                      py_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
entrypoints               0.3                   py38_1000    conda-forge
icu                       64.2                 he025d50_1    conda-forge
ipykernel                 5.1.3            py38h5ca1d4c_0    conda-forge
ipython                   7.11.1           py38h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.15.2                   py38_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
jupyter_client            5.3.4                    py38_1    conda-forge
jupyter_core              4.6.1                    py38_0    conda-forge
libclang                  9.0.1           default_hf44288c_0    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
libsodium                 1.0.17               h2fa13f4_0    conda-forge
openssl                   1.1.1d               hfa6e2cd_0    conda-forge
parso                     0.5.2                      py_0    conda-forge
pickleshare               0.7.5                 py38_1000    conda-forge
pip                       20.0.2                   py38_0    conda-forge
prompt_toolkit            3.0.2                      py_0    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pyqt                      5.12.3           py38h6538335_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
python                    3.8.1                he1f5543_1    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pywin32                   225              py38hfa6e2cd_0    conda-forge
pyzmq                     18.1.1           py38h16f9016_0    conda-forge
qt                        5.12.5               h7ef1ec2_0    conda-forge
qtconsole                 4.6.0                      py_0    conda-forge
setuptools                45.1.0                   py38_0    conda-forge
six                       1.14.0                   py38_0    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
tornado                   6.0.3            py38hfa6e2cd_0    conda-forge
traitlets                 4.3.3                    py38_0    conda-forge
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.16.27012          hf0eaf9b_1  
wcwidth                   0.1.8                      py_0    conda-forge
wheel                     0.33.6                   py38_0    conda-forge
wincertstore              0.2                   py38_1003    conda-forge
zeromq                    4.3.2                h6538335_2    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge

```

**Comment by ccordoba12** [comment]
This is not an issue that can't be solved here.

**Comment by ericpre** [comment]
Thanks for the quick reply @ccordoba12. Do you know where it should be fixed?

Does the same apply to https://github.com/jupyter/qtconsole/issues/400?

**Comment by ccordoba12** [comment]
According to ipython/ipykernel#456, the problem is already solved but a new release of ipykernel is pending.

**Comment by ericpre** [comment]
I have tried to use the master branch of https://github.com/ipython/ipykernel and I still have the same issue. I will check cross time and raise the issue there if this is confirmed.

**Comment by ccordoba12** [comment]
Then you could open an issue in [pyzmq](https://github.com/zeromq/pyzmq) because the error seems to be originating there:

```
File "C:\Users\Eric\Miniconda3\envs\py38qt\lib\site-packages\zmq\eventloop\zmqstream.py", line 546, in _init_io_state
    self.io_loop.add_handler(self.socket, self._handle_events, self.io_loop.READ)
```

**Comment by ericpre** [comment]
Accordingly to https://github.com/tornadoweb/tornado/issues/2608#issuecomment-504689342 and to https://github.com/ipython/ipykernel/pull/480#issuecomment-578690450, the fix needs to be introduce earlier enough, typically when the app object is created. Would it be sensible to introduce the fix in https://github.com/jupyter/qtconsole/blob/270330f6c482b2c7b3ba849f95a75e2055af7e47/qtconsole/qtconsoleapp.py#L261

**Comment by ccordoba12** [comment]
I have no idea, sorry.
